runtime: nodejs18

env_variables:
  NODE_ENV: production
  DOMAIN_URL: "https://tk-chat.netlify.app"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 